version: '3.8'

#Docker Networks
networks:
  laravel:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

# Workflow
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.6
    ports:
      - "3386:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel 
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
